YoshithaRathnayake/NEW-YOSHITHA-WEBSITE

.github/ISSUE_TEMPLATE/custom.md

Add custom issue templates

---

.github/ISSUE_TEMPLATE/bug_report.md

Add bug report templates

---

.github/ISSUE_TEMPLATE/feature_request.md

Add feature request templates

---

.github/pull_request_template.md

Add pull request templates

---

README.md

Customize the main title in README.md file

Customize the main title in README.md file

---

.github/workflows/main.yml

Create new workflows

---

index.html

The purpose of this Pull Request is to fix #24 
Create new index.html file
Create new index.html file
https://pr-27-NEW-YOSHITHA-WEBSITE.surge.sh

Create new index.html file

---

assets/styles.css

Create styles.css file

---

assets/app.js

Create app.js file

---

README.md

Change the description in readme.md file

Change the description in readme.md file

---

README.md

Change the available at link

---

assets/app.js
assets/styles.css

Delete assets directory

---

README.md

Update programming languages

---

index.html

The purpose of this Pull Request is to fix #60
Format the website code
Format the website code
https://pr-59-NEW-YOSHITHA-WEBSITE.surge.sh

Format the website code

---

dark/index.html

The purpose of this Pull Request is to fix #71 
Updated the about-me description in html and meta description tags
The changes are done directly to about section in html file
https://pr-72-NEW-YOSHITHA-WEBSITE.surge.sh

Updated about section with new content

---

dark/index.html

The purpose of this Pull Request is to fix #90 
This fixes the navbar link to contact section
Updated the nav link href to contact section ID
https://pr-91-NEW-YOSHITHA-WEBSITE.surge.sh

Contact navbar link updated

---

dark/assets/css/styles.css

The purpose of this Pull Request is to fix #75
As you asked I have changed the font-family in the about section description.
https://pr-77-NEW-YOSHITHA-WEBSITE.surge.sh

Update the font type of About section

---

dark/index.html

The purpose of this Pull Request is to fix #<issue-number>
https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh

Updated index.html

---

dark/assets/css/styles.css

The purpose of this Pull Request is to fix #107
The about me text can be more attractive
Just remove the italic font style and change the font family using css import to import a Google Font, Kanit to make the text beautiful
https://pr-109-NEW-YOSHITHA-WEBSITE.surge.sh

:lipstick: feat: change about me font family and style

---

README.md
index.html

The purpose of this Pull Request is to fix #111
Fixing age from readme and index.html file
Fixed age from readme and index.html file

Fix age from readme and index.html file

---

README.md

I have updated the README.md file.
I fixed the bug mentioned in the issue. The title and the description are not stuck together anymore.

```Clone your forked repository``` section and description are not stuck together now

---

dark/assets/css/styles.css
dark/index.html
index.html

Add a sentence to contact section

Add a sentence to contact section

---

README.md

add the "and" word in used programming languages sentence.

Use an and between the Bootstrap and Yaml in the readme.md file

---

dark/assets/css/styles.css
dark/index.html

Add the email address with icon in the contact section
The purpose of this Pull Request is to fix #86 
To innovate the contact section by adding the email address
Creating the tags and using Itag adding email icons and email addresses. 
https://pr-123-NEW-YOSHITHA-WEBSITE.surge.sh

added email  in contact section

---

dark/assets/css/styles.css
dark/index.html

The purpose of this Pull Request is to fix #134 
JUST ADDING THE DESIRED TEXT-COLOR,FONT-FAMILY TO THE CONTACT PAGE CSS TEXT.
https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh/

Change the text color in the contact-section to white

---

.github/pull_request_template.md

Add a new comment for the Preview Link section in PR Template

Add a new comment for the Preview Link section in PR Template

---

assets/css/styles.css
dark/assets/css/styles.css
light/assets/css/styles.css

Change the selection color of the text

Change the selection color of the text

---

assets/css/styles.css
light/assets/css/styles.css

Add colour variables

---

dark/index.html

The purpose of this Pull Request is to fix #151<issue-number>
One icon tag is used extra in the html file which needs to be removed
One icon tag is used extra in the html file which needs to be removed
https://pr-152-NEW-YOSHITHA-WEBSITE.surge.sh/dark

Remove the unwanted email icon

---

dark/index.html

The purpose of this Pull Request is to fix #154 <issue-number>
https://pr-157-NEW-YOSHITHA-WEBSITE.surge.sh/

Remove unwanted link tag from the contact section

---

dark/index.html

The purpose of this Pull Request is to fix #155 <issue-number>
https://pr-156-NEW-YOSHITHA-WEBSITE.surge.sh/

Increase the gap between the email and the text in the contact text

---

dark/assets/js/app.js
dark/index.html

The purpose of this Pull Request is to fix #162 
When nav links are clicked it takes to you to the relevant section of the page.
Fixed some errors in dark/index.html file where there were redundant id(s) mentioned at wrong places.
https://pr-163-NEW-YOSHITHA-WEBSITE.surge.sh/
Ubuntu
Review of the code

Fix the navbar links redirecting problem

---

index.html

The purpose of this Pull Request is to fix #160 <issue-number>
https://pr-169-NEW-YOSHITHA-WEBSITE.surge.sh/

Remove the background music code from index.html

---

index.html

The purpose of this Pull Request is to fix #161 <issue-number>
https://pr-170-NEW-YOSHITHA-WEBSITE.surge.sh/

Remove the Elfsight app script tag from index.html

---

dark/index.html

The purpose of this Pull Request is to fix #164 <issue-number>
Only some code to show the background need to to be update
A new tag (h1) is required and need to insert in the section tag 
https://pr-172-NEW-YOSHITHA-WEBSITE.surge.sh/

Add the contact section heading background text

---

dark/index.html

Icon of telegram is wrong and it need to be replaced with other link
The purpose of this Pull Request is to fix #166 <issue-number>
Icon of telegram is wrong and it need to be replaced with other link
Simply change the link of source image
https://pr-171-NEW-YOSHITHA-WEBSITE.surge.sh/

Change the telegram icon in the social media icons

---

dark/index.html

The purpose of this Pull Request is to fix #167 <issue-number>
- This features will fix the instagram icon loading in the social media icons.
- Adding the new png link in the index.html file.
https://pr-174-NEW-YOSHITHA-WEBSITE.surge.sh/

Instagram icon was added in index.html

---

dark/index.html

The purpose of this Pull Request is to fix #168 <issue-number>
- This feature will fix the GitHub icon loading in the social media icons.
- Adding the new png link in the index.html file.
https://pr-176-NEW-YOSHITHA-WEBSITE.surge.sh/

Add Github icon to the index.html

---

dark/index.html

Remove the parents' names from about me description
This fix #83

Remove the parents' names from about me description

---

dark/assets/css/styles.css

Decrease the font weight of the about me description paragraph little bit more
This fix #110

Decrease the font weight of the about me description paragraph little bit more

---

dark/assets/css/styles.css

About Me description is aligned to top little bit more
This fix #184

About Me description is aligned to top little bit more

---

dark/assets/css/styles.css

Reduce the font weight of the contact text
This fix #186

Reduce the font weight of the contact text

---

dark/index.html

Change and edit the contact text
fix #188

Change and edit the contact text

---

dark/assets/css/styles.css

Remove unwanted codes in the css file
fix #190

Remove unwanted codes in the css file

---

dark/index.html

Reduce the border radius in the form in the contact section
fix #192

Reduce the border radius in the form in the contact section

---

dark/index.html
index.html

Make the codes that got two lines for an element as a one line
fix #173

Make the codes that got two lines for an element as a one line

---

light/index.html

Update the code in the light theme
fix #196

Update the code in the light theme

---

dark/index.html

Remove unwanted comments from index.html file
fix #198

Remove unwanted comments from index.html file

---

dark/index.html
index.html

Add required comments to the index.html file
fix #200

Add required comments to the index.html file

---

light/index.html

Add missing tags to index.html files
fix #202

Add missing tags to index.html files

---

.idea/.gitignore
.idea/NEW-YOSHITHA-WEBSITE.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml

Remove unwanted directories
fix #204

Remove unwanted directories

---

dark/assets/css/styles.css
dark/index.html

The purpose of this Pull Request is to fix #143 <issue-number>
- This feature will fix the background of the contact section.
- Adding CSS property to the contact section class name.
https://pr-180-NEW-YOSHITHA-WEBSITE.surge.sh/

Add the background colour to the contact section text

---

index.html

Add new twitter meta tags
Fix #210

Add new twitter meta tags

---

dark/index.html

The purpose of this Pull Request is to fix #227 
https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh/

changed yt link

---

dark/index.html

The purpose of this Pull Request is to fix #226 
Upon clicking the medium link, the medium page will open in a new tab.
https://pr-234-NEW-YOSHITHA-WEBSITE.surge.sh/

[fix]: Added target as blank for medium link

---

dark/index.html

The purpose of this Pull Request is to fix #225 
Replaced the correct link link in the <img> tag

Modified the instagaram link

---

dark/assets/css/styles.css

The purpose of this Pull Request is to fix #229 
Changed the font for Auto-type
https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh/

Changed font color of the Auto-Type

---

dark/index.html

The purpose of this Pull Request is to fix #<issue-number>
https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh/

Fix: Issue #222(changed Twitter link)

---

dark/assets/css/styles.css
dark/index.html

The purpose of this Pull Request is to fix 241
Aligns the social media icons to the center
No need to use the left margin instead use the justify-content property
https://pr-240-NEW-YOSHITHA-WEBSITE.surge.sh/

CSS: Center the social media icons

---

dark/index.html

The purpose of this Pull Request is to fix #224
This PR changes the current LinkedIn profile link with the new one.

Fix LinkedIn Profile Link

---

README.md

Add apostrophe

---

README.md

Change the about
